language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g karma-cli

install:
  - npm install

script:
  - karma start tests/karma-travis.js main
  - karma start tests/karma-travis.js ie

env:
  global:
    - secure: FTpJDb54mevlN12OgAcLBksRLhaOwezKb+9BDKPL1kFJROddf2aNbkXY3mEazM1xgLu0KX3Uqj++Y0v0Ohdmhdz3Pp5BW55+4gjLaf/a+WKuILnSLfs6CAKpcJdbt89oAE4utY6vYFlFafIej9eXCfbgr/9JOA8f6Ww2gdURlgE=
    - secure: cHrZBq+vreOUmi9ls/EMJQD64kLT7E9LzB2YatN9X/h4JBvt1FEJ1MdEWJA13/+BeqWLgjMxPod+/gk8E0Ti+WtDUjbbwqrosOdpFLxm0CFvX0adBWTnphOQxOq1ZyPN/a3zG9dxjDEeFT066809afhqbFf1k1x/661szN6chDE=
